import Head from "next/head";
import React from "react";

const Upload = () => {
  return (
    <div>
      <Head>
        <title>Upload</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Upload</div>
    </div>
  );
};

export default Upload;
